package za.co.rsacraft.cobblepuncher;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockState;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class CobblePuncher extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getLogger().info("CobblePuncher Enabled");
        getServer().getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        getLogger().info("CobblePuncher Disabled");
    }

    @EventHandler
    public void onBlockBreak(BlockBreakEvent event) {
        // Check if the broken block is cobblestone and the player is mining it by hand
        Block brokenBlock = event.getBlock();

        // Check if the player is holding an item in their main hand
        if (event.getPlayer().getInventory().getItemInMainHand().getType() == Material.AIR
                && brokenBlock.getType() == Material.COBBLESTONE) {

            // Check if cobblestone was generated by lava and water, based on the config option
            boolean onlyCobbleGenerator = getConfig().getBoolean("only-cobble-generator", true);

            if (!onlyCobbleGenerator || wasGeneratedByLavaAndWater(brokenBlock)) {
                // Drop the specified amount of cobblestone
                int dropAmount = getConfig().getInt("drop-amount", 1);
                for (int i = 0; i < dropAmount; i++) {
                    brokenBlock.getWorld().dropItemNaturally(brokenBlock.getLocation(), new org.bukkit.inventory.ItemStack(Material.COBBLESTONE));
                }

                // Perform the default block breaking behavior by not canceling the event
            }
        }
    }

    private boolean wasGeneratedByLavaAndWater(Block cobblestoneBlock) {
        BlockState state = cobblestoneBlock.getState();

        // Check if the cobblestone was generated by lava and water based on block states
        if (state.getBlockData() instanceof org.bukkit.block.data.Levelled levelled) {

            // Check if the block is fully filled, indicating lava and water interaction
            return levelled.getLevel() == levelled.getMaximumLevel();
        }

        return false;
    }
}